// This file is auto-generated by tauri-specta. Do not edit manually.
// Run `npm run tauri dev` to regenerate after changing Rust command signatures.

import { invoke } from "@tauri-apps/api/core";

export type AppStatus = {
  version: string;
  ready: boolean;
};

export const commands = {
  async appStatus(): Promise<AppStatus> {
    return await invoke<AppStatus>("app_status");
  },
};
