// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	appStatus: () => __TAURI_INVOKE<AppStatus>("app_status"),
	preferencesRead: () => typedError<unknown, string>(__TAURI_INVOKE("preferences_read")),
	preferencesWrite: (prefs: unknown) => typedError<null, string>(__TAURI_INVOKE("preferences_write", { prefs })),
	secretSet: (key: string, value: string) => typedError<null, string>(__TAURI_INVOKE("secret_set", { key, value })),
	secretGet: (key: string) => typedError<string | null, string>(__TAURI_INVOKE("secret_get", { key })),
	secretDelete: (key: string) => typedError<null, string>(__TAURI_INVOKE("secret_delete", { key })),
	sharedSettingsGet: (key: string) => typedError<unknown | null, string>(__TAURI_INVOKE("shared_settings_get", { key })),
	sharedSettingsSet: (key: string, value: unknown) => typedError<null, string>(__TAURI_INVOKE("shared_settings_set", { key, value })),
	aiProviderConfigGet: () => typedError<AiProviderConfig, string>(__TAURI_INVOKE("ai_provider_config_get")),
	aiProviderConfigSave: (config: AiProviderConfig) => typedError<null, string>(__TAURI_INVOKE("ai_provider_config_save", { config })),
	aiCredentialSecretSet: (credentialName: string, value: string) => typedError<null, string>(__TAURI_INVOKE("ai_credential_secret_set", { credentialName, value })),
	aiCredentialSecretDelete: (credentialName: string) => typedError<null, string>(__TAURI_INVOKE("ai_credential_secret_delete", { credentialName })),
	aiProfileSmokeTest: (profileName: string) => typedError<SmokeTestResult, string>(__TAURI_INVOKE("ai_profile_smoke_test", { profileName })),
	sourceConfigGet: () => typedError<SourcesConfig, string>(__TAURI_INVOKE("source_config_get")),
	sourceConfigSave: (config: SourcesConfig) => typedError<null, string>(__TAURI_INVOKE("source_config_save", { config })),
	sourceCredentialSecretSet: (sourceId: string, kind: SourceCredentialKind, value: string) => typedError<string, string>(__TAURI_INVOKE("source_credential_secret_set", { sourceId, kind, value })),
	sourceCredentialDelete: (credentialRef: string) => typedError<null, string>(__TAURI_INVOKE("source_credential_delete", { credentialRef })),
	sourceConfigRemove: (sourceId: string) => typedError<null, string>(__TAURI_INVOKE("source_config_remove", { sourceId })),
	/**
	 *  Wipe every row scoped to (source, project) so the next sync re-fetches
	 *  the project from scratch. Source config and credentials are untouched.
	 *  See `sources::reset` for the full table list.
	 */
	jiraSourceResetProjectData: (sourceId: string, projectKey: string) => typedError<ResetJiraProjectCounts, string>(__TAURI_INVOKE("jira_source_reset_project_data", { sourceId, projectKey })),
	jiraSourceTestConnection: (source: JiraSourceConfig, pendingPat: string | null) => typedError<JiraConnectionTestResult, string>(__TAURI_INVOKE("jira_source_test_connection", { source, pendingPat })),
	jiraIssueIngestionRun: (sourceId: string, options: {
	fetch_remote_links?: boolean,
} | null) => typedError<JiraIssueIngestionRunResult, string>(__TAURI_INVOKE("jira_issue_ingestion_run", { sourceId, options })),
	jiraIssueIngestionCancel: (sourceId: string, runId: string) => typedError<null, string>(__TAURI_INVOKE("jira_issue_ingestion_cancel", { sourceId, runId })),
	jiraIssueIngestionStatus: (sourceId: string) => typedError<{
	run_id: string,
	status: string,
	phase: string,
	saved_issues: number,
	total_issues: number | null,
	current_page: number | null,
	total_pages: number | null,
	message: string,
	last_successful_issue_sync_at: string | null,
	error_summary: string | null,
} | null, string>(__TAURI_INVOKE("jira_issue_ingestion_status", { sourceId })),
	jiraIssueIngestionProgress: (sourceId: string) => typedError<{
	run_id: string,
	status: string,
	phase: string,
	saved_issues: number,
	total_issues: number | null,
	current_page: number | null,
	total_pages: number | null,
	message: string,
	last_successful_issue_sync_at: string | null,
	error_summary: string | null,
} | null, string>(__TAURI_INVOKE("jira_issue_ingestion_progress", { sourceId })),
	jiraIssuesList: (filter: JiraIssueListFilter) => typedError<JiraIssueListItem[], string>(__TAURI_INVOKE("jira_issues_list", { filter })),
	collectionViewsList: (entityKind: string) => typedError<CollectionViewRecord[], string>(__TAURI_INVOKE("collection_views_list", { entityKind })),
	collectionViewSave: (view: CollectionViewSaveInput) => typedError<CollectionViewRecord, string>(__TAURI_INVOKE("collection_view_save", { view })),
	collectionViewDelete: (id: string) => typedError<null, string>(__TAURI_INVOKE("collection_view_delete", { id })),
	collectionViewsSeedDefaults: (input: CollectionViewSeedInput) => typedError<CollectionViewRecord[], string>(__TAURI_INVOKE("collection_views_seed_defaults", { input })),
	jiraIssueStatusTimeline: (issueId: string) => typedError<JiraIssueStatusTransition[], string>(__TAURI_INVOKE("jira_issue_status_timeline", { issueId })),
	issueSnapshotsQuery: (filter: IssueSnapshotQuery) => typedError<IssueSnapshotListItem[], string>(__TAURI_INVOKE("issue_snapshots_query", { filter })),
	issueHistoryRetentionGet: () => typedError<IssueHistoryRetentionConfig, string>(__TAURI_INVOKE("issue_history_retention_get")),
	issueHistoryRetentionSave: (config: IssueHistoryRetentionConfig) => typedError<null, string>(__TAURI_INVOKE("issue_history_retention_save", { config })),
	/**
	 *  Trigger a batch embedding refresh. Processes up to `options.limit` pending
	 *  documents (default 25 per call) using the configured AI embedding provider.
	 *  Returns a summary with counts and status. Failures are non-fatal: documents
	 *  revert to pending and the summary's `safe_error` field carries a
	 *  sanitised description.
	 */
	embeddingRefreshRun: (options: EmbeddingRunOptions) => typedError<EmbeddingRunSummary, string>(__TAURI_INVOKE("embedding_refresh_run", { options })),
	/**
	 *  Return counts of indexable documents by embedding status. Pass
	 *  `source_system_id` to scope the query to a single ingestion source.
	 */
	embeddingStatus: (sourceSystemId: string | null) => typedError<EmbeddingStatusSummary, string>(__TAURI_INVOKE("embedding_status", { sourceSystemId })),
	auditLogList: (filter: AuditLogListFilter) => typedError<AuditLogEntry[], string>(__TAURI_INVOKE("audit_log_list", { filter })),
	auditLogMarkReverted: (input: AuditLogMarkRevertedInput) => typedError<AuditLogEntry, string>(__TAURI_INVOKE("audit_log_mark_reverted", { input })),
	jiraUpdateTitle: (input: JiraUpdateTitleInput) => typedError<AuditLogEntry, string>(__TAURI_INVOKE("jira_update_title", { input })),
	jiraUpdateTitleReverse: (input: JiraReverseMutationInput) => typedError<AuditLogEntry, string>(__TAURI_INVOKE("jira_update_title_reverse", { input })),
	jiraUpdateLabels: (input: JiraUpdateLabelsInput) => typedError<AuditLogEntry, string>(__TAURI_INVOKE("jira_update_labels", { input })),
	jiraUpdateLabelsReverse: (input: JiraReverseMutationInput) => typedError<AuditLogEntry, string>(__TAURI_INVOKE("jira_update_labels_reverse", { input })),
	jiraReassign: (input: JiraReassignInput) => typedError<AuditLogEntry, string>(__TAURI_INVOKE("jira_reassign", { input })),
	jiraReassignReverse: (input: JiraReverseMutationInput) => typedError<AuditLogEntry, string>(__TAURI_INVOKE("jira_reassign_reverse", { input })),
	jiraCloseIssue: (input: JiraCloseIssueInput) => typedError<AuditLogEntry, string>(__TAURI_INVOKE("jira_close_issue", { input })),
	jiraCloseIssueReverse: (input: JiraReverseMutationInput) => typedError<AuditLogEntry, string>(__TAURI_INVOKE("jira_close_issue_reverse", { input })),
	jiraLinkAsDuplicate: (input: JiraLinkAsDuplicateInput) => typedError<AuditLogEntry, string>(__TAURI_INVOKE("jira_link_as_duplicate", { input })),
	jiraLinkAsDuplicateReverse: (input: JiraReverseMutationInput) => typedError<AuditLogEntry, string>(__TAURI_INVOKE("jira_link_as_duplicate_reverse", { input })),
	jiraAddComment: (input: JiraAddCommentInput) => typedError<AuditLogEntry, string>(__TAURI_INVOKE("jira_add_comment", { input })),
};

/* Types */
export type AiCredentialConfig = {
	name: string,
	kind: AiCredentialKind,
	source: CredentialSource,
};

export type AiCredentialKind = "ApiKey" | "BearerToken" | "AwsIamProfile";

export type AiEndpointConfig = {
	name: string,
	protocol: AiEndpointProtocol,
	base_url: string,
	credential_ref: string,
};

export type AiEndpointProtocol = "AnthropicMessages" | "OpenAiChatCompletionsCompatible" | "OpenAiEmbeddingsCompatible";

export type AiExecutionMode = "DirectApi";

export type AiProfileConfig = {
	name: string,
	endpoint_ref: string,
	model: string,
	runner: AiRunner,
	execution_mode: AiExecutionMode,
	settings: unknown,
};

export type AiProviderConfig = {
	version: number,
	credentials: AiCredentialConfig[],
	endpoints: AiEndpointConfig[],
	profiles: AiProfileConfig[],
	routing: { [key in string]: string },
};

export type AiRunner = "AnthropicMessages" | "OpenAiChatCompletions" | "OpenAiEmbeddings";

export type AppStatus = {
	version: string,
	ready: boolean,
};

export type AuditLogEntry = {
	id: string,
	batch_id: string,
	action_id: string,
	target_ref: string,
	before_state: AuditState,
	after_state: AuditState,
	reversible: boolean,
	reverted_at: string | null,
	reverted_by_action_id: string | null,
	created_at: string,
	source_feature: string,
};

export type AuditLogListFilter = {
	batch_id: string | null,
	target_ref: string | null,
	reversible: boolean | null,
	created_from: string | null,
	created_to: string | null,
	newest_first: boolean | null,
	limit: number | null,
};

export type AuditLogMarkRevertedInput = {
	id: string,
	reverted_by_action_id: string,
	reverted_at: string | null,
};

export type AuditState = unknown;

export type CollectionViewRecord = {
	id: string,
	entity_kind: string,
	display_name: string,
	position: number,
	is_default: boolean,
	config: unknown,
};

export type CollectionViewSaveInput = {
	id: string,
	entity_kind: string,
	display_name: string,
	position: number,
	is_default: boolean,
	config: unknown,
};

export type CollectionViewSeedInput = {
	entity_kind: string,
	defaults: CollectionViewSaveInput[],
};

export type ConnectionTestStatus = "NotTested" | "Success" | "Error" | "Unavailable";

export type ConnectionTestSummary = {
	status: ConnectionTestStatus,
	tested_at: string,
	message: string,
};

export type CredentialSource = { type: "Keychain"; key_ref: string } | { type: "Env"; var_name: string };

export type EmbeddingRunOptions = {
	source_system_id: string | null,
	entity_kind: string | null,
	limit: number | null,
	force_rebuild: boolean,
};

export type EmbeddingRunStatus = "Complete" | "Running" | "Paused" | "Failed" | "Partial";

export type EmbeddingRunSummary = {
	status: EmbeddingRunStatus,
	scanned: number,
	embedded: number,
	skipped: number,
	failed: number,
	model_id: string,
	/**
	 *  Embedding vector dimension. Stored as `u32` rather than `usize` so
	 *  specta can emit a TypeScript-safe numeric type without BigInt risk.
	 */
	dimension: number,
	safe_error: string | null,
};

export type EmbeddingStatusSummary = {
	pending: number,
	embedding: number,
	embedded: number,
	stale: number,
	failed: number,
	last_embedding_refresh: string | null,
	warning: string | null,
};

export type IssueHistoryRetentionConfig = {
	version: number,
	daily_days: number,
	compact_to_weekly_after_days: number,
	weekly_anchor: string,
};

export type IssueSnapshotListItem = {
	issue_id: string,
	snapshot_date: string,
	key: string | null,
	title: string,
	status_name: string | null,
	state: string,
	assignee_display_name: string | null,
	priority_name: string | null,
	project_key: string | null,
};

export type IssueSnapshotQuery = {
	snapshot_date: string,
	source_id: string | null,
	project_key: string | null,
	status_name: string | null,
	state: string | null,
	assignee_person_id: string | null,
	priority_name: string | null,
	label: string | null,
	sprint_name: string | null,
	product_name: string | null,
	customer_name: string | null,
	limit: number | null,
};

export type JiraAddCommentInput = {
	common: MutationCommonInput,
	body: string,
};

export type JiraAuthConfig = { type: "Pat"; credential_ref: string };

export type JiraCloseIssueInput = {
	common: MutationCommonInput,
	transition_id: string,
	inverse_transition_id: string | null,
	before_status: string,
	after_status: string,
	comment: string | null,
};

export type JiraConnectionErrorCategory = "InvalidUrl" | "AuthFailed" | "Forbidden" | "Network" | "RateLimited" | "Server" | "Unsupported" | "Unavailable" | "MissingCredential";

export type JiraConnectionProject = {
	key: string,
	name: string | null,
	id: string | null,
};

export type JiraConnectionTestResult = {
	status: JiraConnectionTestStatus,
	tested_at: string,
	message: string,
	suggested_fix: string | null,
	projects: JiraConnectionProject[],
	category: JiraConnectionErrorCategory | null,
};

export type JiraConnectionTestStatus = "NotTested" | "Testing" | "Success" | "Error" | "Unavailable";

/**
 *  Opt-in toggles for `jira_issue_ingestion_run`. Currently only
 *  `fetch_remote_links` is wired through; the watcher/vote placeholders in
 *  `JiraIngestionOptions` are not exposed on the command surface yet because
 *  the service does not consume them.
 */
export type JiraIngestionRunOptions = {
	fetch_remote_links?: boolean,
};

export type JiraIssueIngestionProgress = {
	run_id: string,
	status: string,
	phase: string,
	saved_issues: number,
	total_issues: number | null,
	current_page: number | null,
	total_pages: number | null,
	message: string,
	last_successful_issue_sync_at: string | null,
	error_summary: string | null,
};

export type JiraIssueIngestionRunResult = {
	run_id: string,
	status: string,
	saved_issues: number,
	total_issues: number | null,
};

export type JiraIssueListFilter = {
	source_id: string | null,
	project_key: string | null,
	limit: number | null,
};

export type JiraIssueListItem = {
	work_item_id: string,
	key: string,
	title: string,
	status_name: string | null,
	assignee_display_name: string | null,
	updated_at_source: string | null,
	project_key: string | null,
	priority_name: string | null,
	labels: string[],
};

export type JiraIssueStatusTransition = {
	event_id: string,
	issue_id: string,
	occurred_at: string,
	actor_display_name: string | null,
	from_status: string | null,
	to_status: string | null,
	complete: boolean,
};

export type JiraLinkAsDuplicateInput = {
	common: MutationCommonInput,
	target_issue_key: string,
	link_type: string,
	close_transition_id: string | null,
	inverse_transition_id: string | null,
	before_status: string | null,
	after_status: string | null,
};

export type JiraProjectFilter = {
	key: string,
	name: string | null,
	id: string | null,
};

export type JiraReassignInput = {
	common: MutationCommonInput,
	before_assignee_account_id: string | null,
	after_assignee_account_id: string | null,
};

export type JiraReverseMutationInput = {
	common: ReverseCommonInput,
};

export type JiraSourceConfig = {
	id: string,
	name: string,
	enabled: boolean,
	server_url: string,
	auth: JiraAuthConfig,
	projects: JiraProjectFilter[],
	last_connection_test: ConnectionTestSummary | null,
	created_at: string,
	updated_at: string,
};

export type JiraUpdateLabelsInput = {
	common: MutationCommonInput,
	before_labels: string[],
	after_labels: string[],
};

export type JiraUpdateTitleInput = {
	common: MutationCommonInput,
	before_title: string,
	after_title: string,
};

export type MutationCommonInput = {
	source_id: string,
	issue_key: string,
	source_feature: string | null,
	batch_id: string | null,
};

export type ResetJiraProjectCounts = {
	work_items: number,
	work_item_terms: number,
	work_item_relationships: number,
	work_item_comments: number,
	jira_issues: number,
	jira_issue_field_values: number,
	jira_worklogs: number,
	jira_remote_links: number,
	jira_project_field_mappings: number,
	issue_events: number,
	issue_snapshots: number,
	document_embeddings: number,
	indexable_documents: number,
	ingestion_cursors: number,
	ingestion_runs: number,
};

export type ReverseCommonInput = {
	source_id: string,
	audit_entry_id: string,
	source_feature: string | null,
	batch_id: string | null,
};

export type SmokeTestResult = {
	status: SmokeTestStatus,
	profile: string,
	runner: AiRunner,
	execution_mode: AiExecutionMode,
	model: string,
	elapsed_ms: number,
	preview: string | null,
	error: string | null,
	suggested_fix: string | null,
};

export type SmokeTestStatus = "NotRun" | "Running" | "Success" | "Error";

export type SourceConfig = {
	kind: "Jira",
} & JiraSourceConfig;

export type SourceCredentialKind = "JiraPat";

export type SourcesConfig = {
	version: number,
	sources: SourceConfig[],
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

